In [1]:
## Sonar Classification Project ##
#Goal is to predict whether object is rock or mine

Process started


```

```

Sonar signal classification

In [2]:
#importing the dependencies
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.svm import SVC
from sklearn.metrics import accuracy_score, classification_report

In [3]:
#configurations
pd.set_option("display.max_columns",None)
pd.set_option('display.float_format', '{:.3f}'.format)

In [6]:
df=pd.read_csv("/content/sonar_data.csv",header=None)
df.head()

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,42,43,44,45,46,47,48,49,50,51,52,53,54,55,56,57,58,59,60
0,0.020,0.037,0.043,0.021,0.095,0.099,0.154,0.160,0.311,0.211,0.161,0.158,0.224,0.065,0.066,0.227,0.310,0.300,0.508,0.480,0.578,0.507,0.433,0.555,0.671,0.641,0.710,0.808,0.679,0.386,0.131,0.260,0.512,0.755,0.854,0.851,0.669,0.610,0.494,0.274,0.051,0.283,0.282,0.426,0.264,0.139,0.105,0.134,0.038,0.032,0.023,0.003,0.006,0.016,0.007,0.017,0.018,0.008,0.009,0.003,R
1,0.045,0.052,0.084,0.069,0.118,0.258,0.216,0.348,0.334,0.287,0.492,0.655,0.692,0.780,0.746,0.944,1.000,0.887,0.802,0.782,0.521,0.405,0.396,0.391,0.325,0.320,0.327,0.277,0.442,0.203,0.379,0.295,0.198,0.234,0.131,0.418,0.384,0.106,0.184,0.197,0.167,0.058,0.140,0.163,0.062,0.020,0.053,0.074,0.041,0.006,0.013,0.008,0.009,0.005,0.009,0.019,0.014,0.005,0.005,0.004,R
2,0.026,0.058,0.110,0.108,0.097,0.228,0.243,0.377,0.560,0.619,0.633,0.706,0.554,0.532,0.648,0.693,0.676,0.755,0.893,0.862,0.797,0.674,0.429,0.365,0.533,0.241,0.507,0.853,0.604,0.851,0.851,0.504,0.186,0.271,0.423,0.304,0.612,0.676,0.537,0.472,0.465,0.259,0.213,0.222,0.211,0.018,0.135,0.074,0.013,0.011,0.003,0.023,0.017,0.009,0.018,0.024,0.032,0.016,0.009,0.008,R
3,0.010,0.017,0.062,0.021,0.021,0.037,0.110,0.128,0.060,0.126,0.088,0.199,0.018,0.226,0.173,0.213,0.069,0.228,0.406,0.397,0.274,0.369,0.556,0.485,0.314,0.533,0.526,0.252,0.209,0.356,0.626,0.734,0.612,0.350,0.395,0.301,0.541,0.881,0.986,0.917,0.612,0.501,0.321,0.320,0.429,0.365,0.266,0.158,0.068,0.029,0.024,0.012,0.004,0.015,0.009,0.007,0.005,0.004,0.004,0.012,R
4,0.076,0.067,0.048,0.039,0.059,0.065,0.121,0.247,0.356,0.446,0.415,0.395,0.426,0.413,0.453,0.533,0.731,0.619,0.203,0.464,0.415,0.429,0.573,0.540,0.316,0.229,0.700,1.000,0.726,0.472,0.510,0.546,0.288,0.098,0.195,0.418,0.460,0.322,0.283,0.243,0.198,0.244,0.185,0.084,0.069,0.053,0.036,0.009,0.023,0.005,0.016,0.003,0.005,0.011,0.011,0.002,0.007,0.005,0.011,0.009,R

In [7]:
df.columns

Index([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35,
       36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53,
       54, 55, 56, 57, 58, 59, 60],
      dtype='int64')

In [8]:
df.shape

(208, 61)

In [9]:
#EXPLORATORY DATA ANALYSIS

In [10]:
#BASIC DATA OVERVIEW
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 208 entries, 0 to 207
Data columns (total 61 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   0       208 non-null    float64
 1   1       208 non-null    float64
 2   2       208 non-null    float64
 3   3       208 non-null    float64
 4   4       208 non-null    float64
 5   5       208 non-null    float64
 6   6       208 non-null    float64
 7   7       208 non-null    float64
 8   8       208 non-null    float64
 9   9       208 non-null    float64
 10  10      208 non-null    float64
 11  11      208 non-null    float64
 12  12      208 non-null    float64
 13  13      208 non-null    float64
 14  14      208 non-null    float64
 15  15      208 non-null    float64
 16  16      208 non-null    float64
 17  17      208 non-null    float64
 18  18      208 non-null    float64
 19  19      208 non-null    float64
 20  20      208 non-null    float64
 21  21      208 non-null    float64
 22  22      208 non-null    float64
 23  23      208 non-null    float64
 24  24      208 non-null    float64
 25  25      208 non-null    float64
 26  26      208 non-null    float64
 27  27      208 non-null    float64
 28  28      208 non-null    float64
 29  29      208 non-null    float64
 30  30      208 non-null    float64
 31  31      208 non-null    float64
 32  32      208 non-null    float64
 33  33      208 non-null    float64
 34  34      208 non-null    float64
 35  35      208 non-null    float64
 36  36      208 non-null    float64
 37  37      208 non-null    float64
 38  38      208 non-null    float64
 39  39      208 non-null    float64
 40  40      208 non-null    float64
 41  41      208 non-null    float64
 42  42      208 non-null    float64
 43  43      208 non-null    float64
 44  44      208 non-null    float64
 45  45      208 non-null    float64
 46  46      208 non-null    float64
 47  47      208 non-null    float64
 48  48      208 non-null    float64
 49  49      208 non-null    float64
 50  50      208 non-null    float64
 51  51      208 non-null    float64
 52  52      208 non-null    float64
 53  53      208 non-null    float64
 54  54      208 non-null    float64
 55  55      208 non-null    float64
 56  56      208 non-null    float64
 57  57      208 non-null    float64
 58  58      208 non-null    float64
 59  59      208 non-null    float64
 60  60      208 non-null    object
dtypes: float64(60), object(1)
memory usage: 99.3+ KB

In [11]:
#missing value analysis
(df.isnull().sum()/len(df))*100

0    0.000
1    0.000
2    0.000
3    0.000
4    0.000
      ...
56   0.000
57   0.000
58   0.000
59   0.000
60   0.000
Length: 61, dtype: float64

In [12]:
#identify presence of encoded missing values
df.columns

Index([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35,
       36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53,
       54, 55, 56, 57, 58, 59, 60],
      dtype='int64')

In [13]:
for i in df.columns:
  print(df[i].value_counts())

0
0.020    5
0.009    3
0.013    3
0.010    3
0.021    3
        ..
0.027    1
0.019    1
0.032    1
0.052    1
0.030    1
Name: count, Length: 177, dtype: int64
1
0.052    2
0.058    2
0.045    2
0.009    2
0.031    2
        ..
0.039    1
0.026    1
0.035    1
0.010    1
0.035    1
Name: count, Length: 182, dtype: int64
2
0.028    2
0.062    2
0.035    2
0.084    2
0.014    2
        ..
0.033    1
0.049    1
0.017    1
0.018    1
0.049    1
Name: count, Length: 190, dtype: int64
3
0.011    3
0.061    3
0.025    2
0.049    2
0.039    2
        ..
0.057    1
0.085    1
0.018    1
0.056    1
0.029    1
Name: count, Length: 181, dtype: int64
4
0.116    2
0.030    2
0.065    2
0.060    2
0.162    2
        ..
0.039    1
0.076    1
0.035    1
0.017    1
0.021    1
Name: count, Length: 193, dtype: int64
5
0.044    2
0.053    2
0.077    2
0.028    2
0.069    2
        ..
0.163    1
0.096    1
0.117    1
0.135    1
0.034    1
Name: count, Length: 196, dtype: int64
6
0.077    3
0.120    2
0.099    2
0.100    2
0.097    2
        ..
0.203    1
0.099    1
0.126    1
0.146    1
0.066    1
Name: count, Length: 195, dtype: int64
7
0.183    2
0.078    2
0.113    2
0.107    2
0.066    2
        ..
0.169    1
0.102    1
0.118    1
0.112    1
0.140    1
Name: count, Length: 201, dtype: int64
8
0.060    2
0.210    2
0.074    2
0.560    1
0.311    1
        ..
0.233    1
0.103    1
0.126    1
0.195    1
0.184    1
Name: count, Length: 205, dtype: int64
9
0.235    2
0.287    1
0.211    1
0.126    1
0.446    1
        ..
0.319    1
0.400    1
0.268    1
0.215    1
0.253    1
Name: count, Length: 207, dtype: int64
10
0.094    2
0.089    2
0.248    2
0.156    2
0.213    2
        ..
0.311    1
0.308    1
0.272    1
0.290    1
0.272    1
Name: count, Length: 203, dtype: int64
11
0.374    2
0.332    2
0.706    1
0.199    1
0.395    1
        ..
0.293    1
0.343    1
0.237    1
0.281    1
0.244    1
Name: count, Length: 206, dtype: int64
12
0.266    3
0.225    2
0.119    2
0.262    2
0.230    2
        ..
0.228    1
0.299    1
0.188    1
0.158    1
0.167    1
Name: count, Length: 198, dtype: int64
13
0.290    2
0.309    2
0.311    2
0.280    2
0.261    2
        ..
0.099    1
0.140    1
0.098    1
0.027    1
0.034    1
Name: count, Length: 202, dtype: int64
14
0.377    2
0.323    2
0.187    2
0.189    2
0.357    2
        ..
0.180    1
0.123    1
0.068    1
0.067    1
0.130    1
Name: count, Length: 203, dtype: int64
15
0.533    2
0.114    2
0.203    2
0.331    2
0.281    2
        ..
0.220    1
0.153    1
0.150    1
0.144    1
0.171    1
Name: count, Length: 203, dtype: int64
16
1.000    4
0.207    2
0.216    2
0.230    2
0.676    1
        ..
0.209    1
0.273    1
0.190    1
0.172    1
0.218    1
Name: count, Length: 202, dtype: int64
17
1.000    3
0.188    2
0.243    2
0.300    1
0.619    1
        ..
0.268    1
0.286    1
0.234    1
0.265    1
0.318    1
Name: count, Length: 204, dtype: int64
18
0.406    2
0.345    2
0.802    1
0.893    1
0.203    1
        ..
0.203    1
0.212    1
0.196    1
0.283    1
0.371    1
Name: count, Length: 206, dtype: int64
19
1.000    2
0.335    2
0.769    2
0.351    2
0.517    2
        ..
0.174    1
0.239    1
0.140    1
0.429    1
0.455    1
Name: count, Length: 203, dtype: int64
20
1.000    9
0.578    1
0.797    1
0.521    1
0.415    1
        ..
0.413    1
0.327    1
0.316    1
0.569    1
0.570    1
Name: count, Length: 200, dtype: int64
21
1.000    6
0.405    1
0.507    1
0.369    1
0.429    1
        ..
0.688    1
0.595    1
0.589    1
0.699    1
0.740    1
Name: count, Length: 203, dtype: int64
22
1.000    7
0.585    2
0.143    2
0.806    2
0.556    1
        ..
0.812    1
0.830    1
0.763    1
0.725    1
0.806    1
Name: count, Length: 199, dtype: int64
23
1.000    7
0.943    2
0.365    1
0.391    1
0.540    1
        ..
0.845    1
0.904    1
0.847    1
0.762    1
0.884    1
Name: count, Length: 201, dtype: int64
24
1.000    7
0.695    2
0.844    2
0.774    2
0.411    2
        ..
0.892    1
0.989    1
0.942    1
0.924    1
0.943    1
Name: count, Length: 198, dtype: int64
25
1.000    11
0.754     2
0.894     2
0.486     2
0.344     2
         ..
0.881     1
0.849     1
0.930     1
0.991     1
0.999     1
Name: count, Length: 194, dtype: int64
26
1.000    17
0.684     2
0.892     2
0.526     1
0.507     1
         ..
0.999     1
0.945     1
0.970     1
0.998     1
0.938     1
Name: count, Length: 190, dtype: int64
27
1.000    12
0.440     2
0.913     2
0.752     2
0.277     1
         ..
0.982     1
0.931     1
0.996     1
0.830     1
0.760     1
Name: count, Length: 194, dtype: int64
28
1.000    8
0.904    3
0.790    2
0.899    2
0.442    1
        ..
0.810    1
0.909    1
0.863    1
0.703    1
0.712    1
Name: count, Length: 197, dtype: int64
29
1.000    6
0.382    2
0.851    1
0.356    1
0.472    1
        ..
0.620    1
0.741    1
0.698    1
0.714    1
0.836    1
Name: count, Length: 202, dtype: int64
30
0.386    2
0.379    1
0.131    1
0.626    1
0.510    1
        ..
0.604    1
0.769    1
0.772    1
0.689    1
0.762    1
Name: count, Length: 207, dtype: int64
31
0.290    2
0.464    2
0.507    2
0.295    1
0.260    1
        ..
0.555    1
0.712    1
0.731    1
0.496    1
0.457    1
Name: count, Length: 205, dtype: int64
32
0.416    2
0.525    2
0.541    2
0.198    1
0.512    1
        ..
0.496    1
0.530    1
0.520    1
0.258    1
0.172    1
Name: count, Length: 205, dtype: int64
33
0.220    2
0.197    2
0.271    1
0.350    1
0.098    1
        ..
0.147    1
0.213    1
0.179    1
0.097    1
0.155    1
Name: count, Length: 206, dtype: int64
34
1.000    3
0.397    2
0.131    1
0.395    1
0.423    1
        ..
0.085    1
0.093    1
0.110    1
0.078    1
0.164    1
Name: count, Length: 205, dtype: int64
35
1.000    2
0.233    2
0.152    2
0.418    1
0.304    1
        ..
0.061    1
0.130    1
0.145    1
0.036    1
0.187    1
Name: count, Length: 205, dtype: int64
36
0.107    2
0.625    2
0.612    1
0.541    1
0.669    1
        ..
0.097    1
0.116    1
0.107    1
0.157    1
0.266    1
Name: count, Length: 206, dtype: int64
37
0.315    2
0.182    2
0.676    1
0.881    1
0.322    1
        ..
0.141    1
0.123    1
0.144    1
0.182    1
0.171    1
Name: count, Length: 206, dtype: int64
38
0.168    2
0.089    2
0.142    2
0.158    2
0.283    1
        ..
0.168    1
0.177    1
0.193    1
0.135    1
0.096    1
Name: count, Length: 204, dtype: int64
39
0.443    2
0.272    2
0.472    1
0.917    1
0.274    1
        ..
0.120    1
0.035    1
0.033    1
0.085    1
0.077    1
Name: count, Length: 206, dtype: int64
40
0.167    2
0.224    2
0.168    2
0.305    2
0.198    1
        ..
0.120    1
0.156    1
0.149    1
0.049    1
0.085    1
Name: count, Length: 204, dtype: int64
41
0.283    1
0.058    1
0.259    1
0.501    1
0.244    1
        ..
0.104    1
0.082    1
0.033    1
0.137    1
0.208    1
Name: count, Length: 208, dtype: int64
42
0.212    2
0.273    2
0.155    2
0.321    1
0.140    1
        ..
0.064    1
0.198    1
0.115    1
0.054    1
0.251    1
Name: count, Length: 205, dtype: int64
43
0.320    2
0.138    2
0.127    2
0.124    2
0.192    2
        ..
0.134    1
0.169    1
0.131    1
0.155    1
0.186    1
Name: count, Length: 196, dtype: int64
44
0.119    2
0.076    2
0.116    2
0.062    1
0.211    1
        ..
0.090    1
0.095    1
0.091    1
0.132    1
0.144    1
Name: count, Length: 205, dtype: int64
45
0.097    2
0.047    2
0.051    2
0.143    2
0.078    2
        ..
0.108    1
0.008    1
0.076    1
0.099    1
0.147    1
Name: count, Length: 199, dtype: int64
46
0.053    2
0.079    2
0.134    2
0.043    2
0.080    2
        ..
0.064    1
0.152    1
0.106    1
0.126    1
0.099    1
Name: count, Length: 202, dtype: int64
47
0.074    2
0.031    2
0.047    2
0.075    2
0.009    1
        ..
0.136    1
0.126    1
0.101    1
0.095    1
0.004    1
Name: count, Length: 204, dtype: int64
48
0.011    3
0.033    3
0.049    2
0.078    2
0.044    2
        ..
0.086    1
0.065    1
0.053    1
0.049    1
0.015    1
Name: count, Length: 193, dtype: int64
49
0.018    5
0.022    4
0.024    3
0.009    3
0.012    3
        ..
0.018    1
0.006    1
0.028    1
0.029    1
0.024    1
Name: count, Length: 154, dtype: int64
50
0.013    4
0.015    4
0.012    3
0.010    3
0.014    3
        ..
0.019    1
0.020    1
0.013    1
0.020    1
0.004    1
Name: count, Length: 160, dtype: int64
51
0.009    5
0.006    4
0.014    4
0.010    4
0.008    4
        ..
0.017    1
0.013    1
0.012    1
0.016    1
0.009    1
Name: count, Length: 144, dtype: int64
52
0.013    5
0.012    4
0.007    4
0.010    4
0.004    3
        ..
0.003    1
0.008    1
0.004    1
0.010    1
0.005    1
Name: count, Length: 134, dtype: int64
53
0.008    5
0.008    4
0.002    4
0.009    4
0.015    4
        ..
0.014    1
0.006    1
0.007    1
0.001    1
0.013    1
Name: count, Length: 134, dtype: int64
54
0.007    5
0.004    5
0.008    4
0.004    4
0.004    4
        ..
0.003    1
0.009    1
0.002    1
0.006    1
0.003    1
Name: count, Length: 129, dtype: int64
55
0.005    5
0.009    4
0.007    4
0.010    4
0.005    4
        ..
0.001    1
0.003    1
0.002    1
0.007    1
0.010    1
Name: count, Length: 122, dtype: int64
56
0.005    7
0.004    7
0.004    5
0.003    4
0.003    4
        ..
0.011    1
0.006    1
0.001    1
0.002    1
0.007    1
Name: count, Length: 121, dtype: int64
57
0.004    6
0.002    5
0.004    4
0.005    4
0.009    4
        ..
0.015    1
0.009    1
0.007    1
0.005    1
0.014    1
Name: count, Length: 124, dtype: int64
58
0.007    6
0.005    5
0.007    5
0.005    5
0.004    5
        ..
0.001    1
0.006    1
0.019    1
0.006    1
0.006    1
Name: count, Length: 119, dtype: int64
59
0.005    7
0.002    6
0.004    5
0.003    5
0.003    5
        ..
0.004    1
0.001    1
0.003    1
0.016    1
0.011    1
Name: count, Length: 109, dtype: int64
60
M    111
R     97
Name: count, dtype: int64

In [14]:
#target distribution check
df[60].value_counts()
print("-----"*30)

------------------------------------------------------------------------------------------------------------------------------------------------------

In [15]:
df[60].value_counts(normalize=True)*100

60
M   53.365
R   46.635
Name: proportion, dtype: float64

In [16]:
#map lables
df[60]=df[60].map({'R':0,'M':1})

In [17]:
print(df[60].value_counts())
print("-----"*30)
print(df[60].value_counts(normalize=True)*100)

60
1    111
0     97
Name: count, dtype: int64
------------------------------------------------------------------------------------------------------------------------------------------------------
60
1   53.365
0   46.635
Name: proportion, dtype: float64

In [18]:
#identifying duplicate rows
df.duplicated().value_counts()

False    208
Name: count, dtype: int64

In [19]:
Number_of_duplicates=df.duplicated().sum()

In [20]:
print("Duplicate rows:", df[df.duplicated()])

Duplicate rows: Empty DataFrame
Columns: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60]
Index: []

In [21]:
#constant and quassi constant columns
#identify columns that has almost similar values throughout
# Find names of constant columns


df.columns[df.nunique()==1]

Index([], dtype='int64')

In [22]:
for i in df.columns:
  print(i,df[i].nunique())

0 177
1 182
2 190
3 181
4 193
5 196
6 195
7 201
8 205
9 207
10 203
11 206
12 198
13 202
14 203
15 203
16 202
17 204
18 206
19 203
20 200
21 203
22 199
23 201
24 198
25 194
26 190
27 194
28 197
29 202
30 207
31 205
32 205
33 206
34 205
35 205
36 206
37 206
38 204
39 206
40 204
41 208
42 205
43 196
44 205
45 199
46 202
47 204
48 193
49 154
50 160
51 144
52 134
53 134
54 129
55 122
56 121
57 124
58 119
59 109
60 2

In [23]:
for i in df.columns:
    freq = (df[i].value_counts(normalize=True)*100).max()

    if freq <= 0.99:
        print(i,freq)

1 0.9615384615384616
2 0.9615384615384616
4 0.9615384615384616
5 0.9615384615384616
7 0.9615384615384616
8 0.9615384615384616
9 0.9615384615384616
10 0.9615384615384616
11 0.9615384615384616
13 0.9615384615384616
14 0.9615384615384616
15 0.9615384615384616
18 0.9615384615384616
19 0.9615384615384616
30 0.9615384615384616
31 0.9615384615384616
32 0.9615384615384616
33 0.9615384615384616
35 0.9615384615384616
36 0.9615384615384616
37 0.9615384615384616
38 0.9615384615384616
39 0.9615384615384616
40 0.9615384615384616
41 0.4807692307692308
42 0.9615384615384616
43 0.9615384615384616
44 0.9615384615384616
45 0.9615384615384616
46 0.9615384615384616
47 0.9615384615384616

In [24]:
#group the features based on mean of feature for class 1 0r 0
df.groupby(60).mean().T

60     0     1
0  0.022 0.035
1  0.030 0.046
2  0.036 0.051
3  0.041 0.065
4  0.062 0.087
5  0.096 0.112
6  0.114 0.128
7  0.118 0.150
8  0.137 0.213
9  0.159 0.251
10 0.175 0.290
11 0.192 0.301
12 0.226 0.314
13 0.269 0.321
14 0.308 0.331
15 0.376 0.381
16 0.417 0.415
17 0.448 0.456
18 0.467 0.538
19 0.500 0.618
20 0.542 0.667
21 0.569 0.672
22 0.613 0.677
23 0.654 0.689
24 0.669 0.681
25 0.693 0.706
26 0.688 0.715
27 0.673 0.712
28 0.633 0.650
29 0.580 0.582
30 0.530 0.482
31 0.452 0.428
32 0.441 0.397
33 0.446 0.366
34 0.456 0.338
35 0.461 0.319
36 0.417 0.317
37 0.349 0.332
38 0.314 0.336
39 0.318 0.305
40 0.285 0.293
41 0.252 0.301
42 0.212 0.277
43 0.175 0.248
44 0.142 0.245
45 0.117 0.199
46 0.094 0.147
47 0.069 0.111
48 0.038 0.064
49 0.018 0.023
50 0.012 0.019
51 0.010 0.016
52 0.010 0.012
53 0.010 0.012
54 0.009 0.010
55 0.007 0.009
56 0.008 0.008
57 0.007 0.009
58 0.007 0.009
59 0.006 0.007

In [25]:
#data preprocessing
#seperate x and y column
X=df.drop(columns=[60])
y=df[60]

In [26]:
#TRAIN TEST SPLIT
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,stratify=y,random_state=42)

In [27]:
X_train.shape

(166, 60)

In [28]:
X_test.shape

(42, 60)

In [29]:
#feature scaling
scaler=StandardScaler()

In [30]:
X_train_scaled=scaler.fit_transform(X_train)
X_test_scaled=scaler.transform(X_test)

In [31]:
#model training
model=SVC()

In [32]:
#train the model
model.fit(X_train_scaled,y_train)

SVC()

In [33]:
#model evaluation
y_train_pred=model.predict(X_train_scaled)
model_accuracy_training=classification_report(y_train,y_train_pred)
print(accuracy_score)
print("-----"*30)
print(model_accuracy_training)

<function accuracy_score at 0x78d9fd772660>
------------------------------------------------------------------------------------------------------------------------------------------------------
              precision    recall  f1-score   support

           0       0.94      1.00      0.97        77
           1       1.00      0.94      0.97        89

    accuracy                           0.97       166
   macro avg       0.97      0.97      0.97       166
weighted avg       0.97      0.97      0.97       166

In [34]:
#now evaluation for predictaion
y_test_pred=model.predict(X_test_scaled)
model_accuracy_testing=classification_report(y_test,y_test_pred)
print("-----"*30)
print(model_accuracy_testing)

------------------------------------------------------------------------------------------------------------------------------------------------------
              precision    recall  f1-score   support

           0       1.00      0.85      0.92        20
           1       0.88      1.00      0.94        22

    accuracy                           0.93        42
   macro avg       0.94      0.93      0.93        42
weighted avg       0.94      0.93      0.93        42

In [35]:
#building a prediction system
def predict_object(input_features):
  #scale features
  scaled_features=scaler.transform([input_features])
  #get prediction from model
  prediction=model.predict(scaled_features)
  print(prediction)
  if prediction[0]==0:
    print("The object is a rock")
  else:
    print("The object is a mine")

In [36]:
X_test.head()

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,42,43,44,45,46,47,48,49,50,51,52,53,54,55,56,57,58,59
103,0.016,0.025,0.026,0.039,0.065,0.047,0.106,0.139,0.060,0.133,0.297,0.475,0.568,0.569,0.642,0.749,0.900,1.000,0.969,0.903,0.768,0.700,0.664,0.596,0.371,0.092,0.048,0.088,0.104,0.171,0.326,0.461,0.394,0.505,0.483,0.351,0.232,0.403,0.368,0.151,0.074,0.140,0.155,0.038,0.064,0.044,0.026,0.022,0.019,0.008,0.014,0.007,0.008,0.023,0.020,0.007,0.004,0.010,0.005,0.002
168,0.002,0.019,0.029,0.019,0.051,0.082,0.101,0.012,0.117,0.148,0.212,0.258,0.235,0.133,0.009,0.195,0.368,0.465,0.542,0.626,0.742,0.826,0.861,0.840,0.895,0.995,1.000,0.965,0.875,0.626,0.218,0.294,0.364,0.501,0.784,0.936,0.820,0.621,0.451,0.300,0.267,0.224,0.314,0.369,0.299,0.223,0.085,0.036,0.029,0.012,0.004,0.011,0.007,0.009,0.004,0.003,0.001,0.001,0.003,0.005
129,0.137,0.123,0.139,0.148,0.178,0.143,0.177,0.216,0.163,0.207,0.426,0.548,0.713,0.700,0.678,0.794,0.938,0.892,0.915,0.783,0.796,0.798,0.772,0.661,0.486,0.557,0.470,0.564,0.452,0.337,0.268,0.234,0.305,0.302,0.275,0.104,0.176,0.316,0.360,0.274,0.130,0.246,0.340,0.175,0.068,0.106,0.064,0.053,0.053,0.027,0.017,0.012,0.013,0.034,0.006,0.007,0.002,0.008,0.015,0.005
182,0.009,0.031,0.054,0.041,0.061,0.104,0.102,0.139,0.259,0.374,0.423,0.450,0.540,0.430,0.333,0.350,0.343,0.285,0.406,0.683,0.765,0.667,0.570,0.600,0.648,0.861,0.982,0.938,0.844,0.607,0.540,0.689,0.598,0.324,0.052,0.316,0.359,0.388,0.572,0.431,0.305,0.439,0.430,0.483,0.508,0.195,0.154,0.204,0.105,0.025,0.036,0.018,0.002,0.010,0.013,0.004,0.004,0.003,0.003,0.003
90,0.013,0.052,0.062,0.052,0.107,0.259,0.230,0.207,0.342,0.428,0.301,0.121,0.330,0.571,0.696,0.975,1.000,0.929,0.621,0.459,0.500,0.503,0.708,0.842,0.811,0.769,0.810,0.620,0.236,0.260,0.630,0.676,0.290,0.439,0.853,0.718,0.480,0.586,0.499,0.287,0.060,0.117,0.274,0.281,0.208,0.066,0.049,0.035,0.017,0.029,0.003,0.021,0.005,0.020,0.013,0.002,0.004,0.003,0.011,0.008

In [37]:
y_test.head()

103    1
168    1
129    1
182    1
90     0
Name: 60, dtype: int64

In [38]:
#sample prediction
test_input=X_test.loc[103].tolist()
print(test_input)

[0.0162, 0.0253, 0.0262, 0.0386, 0.0645, 0.0472, 0.1056, 0.1388, 0.0598, 0.1334, 0.2969, 0.4754, 0.5677, 0.569, 0.6421, 0.7487, 0.8999, 1.0, 0.969, 0.9032, 0.7685, 0.6998, 0.6644, 0.5964, 0.3711, 0.0921, 0.0481, 0.0876, 0.104, 0.1714, 0.3264, 0.4612, 0.3939, 0.505, 0.4833, 0.3511, 0.2319, 0.4029, 0.3676, 0.151, 0.0745, 0.1395, 0.1552, 0.0377, 0.0636, 0.0443, 0.0264, 0.0223, 0.0187, 0.0077, 0.0137, 0.0071, 0.0082, 0.0232, 0.0198, 0.0074, 0.0035, 0.01, 0.0048, 0.0019]

In [39]:
predict_object(test_input)

[1]
The object is a mine